INSERT INTO APP_USER (ID, USERNAME, CREATED_AT)
SELECT 1,
       'admin',
       CURRENT_TIMESTAMP
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
    SELECT *
    FROM APP_USER
    WHERE USERNAME = 'admin'
);
